version: "3.1"

services:
  app:
    container_name: wordpress
    build:
      context: .
      dockerfile: ./php.dockerfile
    restart: always
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - ./site/:/var/www/html
    networks:
      - wordpress

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: wordpress_local
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - wordpress
volumes:
  mysql:
networks:
  wordpress:
